### PR TITLE
Add support for Hitachi Deskstar 7K3000, Western Digital Green, Toshiba 3.5\" DT01ACA... Desktop HDD, and Intel 540 Series SSD

### PR DESCRIPTION
**Pull request by horazont**
No thresholds and perfs for the intel SSDs because we configure those differently.

### CODE REVIEW

**Comment by gschoenberger** [comment]
I think we cannot merge commit 357fcd8baeefcfc3c94784ee24a38594fd7bc52b
The "r8" is added intentionally, some raw values require bit rotation. With "r8" you configure that you want to shift the raw value eight positions to the right.

**Comment by horazont** [comment]
@gschoenberger Ah, I haven’t found that behaviour documented anywhere and assumed it was some kind of typo.

I’ll fix the PR in the next days, thanks for the feedback.

**Comment by gschoenberger** [comment]
@horazont Yeah, I think I have to document that! It was a quick fix for a SSD as far as I can remember.
The corresponding code starts at line 308:
```
if($shift_dir eq 'l'){
	$row->{$IDs_h{$ID}} = $row->{$IDs_h{$ID}} << $2;
}
if($shift_dir eq 'r'){
	$row->{$IDs_h{$ID}} = $row->{$IDs_h{$ID}} >> $2;
}
```

**Comment by horazont** [comment]
@gschoenberger I removed the problematic commit. Is there anything else which needs to be changed?

**Pull request merged**
